name: Release caarea-vlib

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Yarn install dependencies
      run: yarn install

    - name: Linter validation
      run: yarn run lint:check

    - name: Build package
      run: yarn run build